testname: My TTS Listening Test
testId: my_tts_test
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php

pages:
- type: generic
  id: first_page
  name: Welcome
  content: Welcome to the listening test! Please follow the instructions and rate
    the samples.

####################################### MOS test ##################################################

### BAS ###

- type: mushra
  id: page1
  name: MUSHRA page1
  content: Please rate how natural each sample sounds. You may use the full range of the scale to indicate your preferences. Higher scores correspond to a more natural-sounding voice.
  showWaveform: true
  enableLooping: false
  reference: configs/resources/audio/RT_swara/originals/bas/bas_rnd2_456.wav
  stimuli:
    FASTPITCH: configs/resources/audio/RT_swara/FASTPITCH/bas/10/bas_rnd2_456_gen.wav
    Grad-TTS: configs/resources/audio/RT_swara/Grad-TTS/bas/10/bas_rnd2_456.wav
    Matcha-TTS: configs/resources/audio/RT_swara/Matcha-TTS/bas/10/bas_rnd2_456.wav
    VITS: configs/resources/audio/RT_swara/VITS/bas/10/bas_rnd2_456_gen.wav
  createAnchor35: false
  createAnchor70: false
  switchBack: true

- type: bs1116
  id: page2
  name: MUSHRA page2
  content: Please rate how natural each sample sounds. You may use the full range of the scale to indicate your preferences. Higher scores correspond to a more natural-sounding voice.
  showWaveform: true
  enableLooping: false
  reference: configs/resources/audio/RT_swara/originals/bas/bas_rnd2_479.wav
  stimuli:
    FASTPITCH: configs/resources/audio/RT_swara/FASTPITCH/bas/10/bas_rnd2_479_gen.wav
    Grad-TTS: configs/resources/audio/RT_swara/Grad-TTS/bas/10/bas_rnd2_479.wav
    Matcha-TTS: configs/resources/audio/RT_swara/Matcha-TTS/bas/10/bas_rnd2_479.wav
    VITS: configs/resources/audio/RT_swara/VITS/bas/10/bas_rnd2_479_gen.wav
  createAnchor35: false
  createAnchor70: false

- type: paired_comparison
  id: page3
  name: MUSHRA page3
  content: Please rate how natural each sample sounds. You may use the full range of the scale to indicate your preferences. Higher scores correspond to a more natural-sounding voice.
  showWaveform: true
  enableLooping: false
  reference: configs/resources/audio/RT_swara/originals/bas/bas_rnd2_468.wav
  stimuli:
    FASTPITCH: configs/resources/audio/RT_swara/FASTPITCH/bas/10/bas_rnd2_468_gen.wav
    Grad-TTS: configs/resources/audio/RT_swara/Grad-TTS/bas/10/bas_rnd2_468.wav
    Matcha-TTS: configs/resources/audio/RT_swara/Matcha-TTS/bas/10/bas_rnd2_468.wav
    VITS: configs/resources/audio/RT_swara/VITS/bas/10/bas_rnd2_468_gen.wav
  createAnchor35: false
  createAnchor70: false

- type: likert_multi_stimulus
  id: page4
  name: MUSHRA page4
  content: Please rate how natural each sample sounds. You may use the full range of the scale to indicate your preferences. Higher scores correspond to a more natural-sounding voice.
  mustRate: true
  mustPlayback: processUpdate
  stimuli:
    reference: configs/resources/audio/RT_swara/originals/bas/bas_rnd2_494.wav
    FASTPITCH: configs/resources/audio/RT_swara/FASTPITCH/bas/10/bas_rnd2_494_gen.wav
    Grad-TTS: configs/resources/audio/RT_swara/Grad-TTS/bas/10/bas_rnd2_494.wav
    Matcha-TTS: configs/resources/audio/RT_swara/Matcha-TTS/bas/10/bas_rnd2_494.wav
    VITS: configs/resources/audio/RT_swara/VITS/bas/10/bas_rnd2_494_gen.wav
  
  response:
    - value: not at all
      label: Not at all
      img: configs/resources/images/star_off.png
      imgSelected: configs/resources/images/star_on.png
      imgHigherResponseSelected: configs/resources/images/star_on.png
    - value: not a lot
      label: Not a lot
      img: configs/resources/images/star_off.png
      imgSelected: configs/resources/images/star_on.png
      imgHigherResponseSelected: configs/resources/images/star_on.png
    - value: a bit
      label: A bit
      img: configs/resources/images/star_off.png
      imgSelected: configs/resources/images/star_on.png
      imgHigherResponseSelected: configs/resources/images/star_on.png
    - value: much
      label: Much
      img: configs/resources/images/star_off.png
      imgSelected: configs/resources/images/star_on.png
      imgHigherResponseSelected: configs/resources/images/star_on.png   
  
- type: finish
  name: Thank you
  content: Thank you for attending!
  showResults: true
  writeResults: true
  questionnaire:
  - type: text
    label: eMail
    name: email
  - type: number
    label: Age
    name: age
    min: 0
    max: 100
    default: 30
  - type: likert
    name: gender
    label: Gender
    response:
    - value: female
      label: Female
    - value: male
      label: Male
    - value: other
      label: Other
