testname: My TTS Listening Test
testId: my_tts_test
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php

pages:
    - type: generic
      id: first_page
      name: Welcome
      content: Welcome to the listening test! Please follow the instructions and rate the samples.

    - type: mushra
      id: trial1
      name: MUSHRA Test
      content: In this test, please rate the quality of each sample compared to the reference.
      showWaveform: true
      enableLooping: true
      reference: configs/resources/audio/mono_ref.wav
      stimuli:
          C1: configs/resources/audio/FASTPITCH/bas/bas_rnd2_455_gen.wav
          C2: configs/resources/audio/FASTPITCH/bas/bas_rnd2_456_gen.wav
          C3: configs/resources/audio/FASTPITCH/bas/bas_rnd2_457_gen.wav
          C4: configs/resources/audio/FASTPITCH/bas/bas_rnd2_455_gen.wav
          C5: configs/resources/audio/FASTPITCH/bas/bas_rnd2_456_gen.wav
          C6: configs/resources/audio/FASTPITCH/bas/bas_rnd2_457_gen.wav
      createAnchor35: false
      createAnchor70: false

    - type: finish
      name: Thank you
      content: Thank you for attending!
      showResults: true
      writeResults: true
      questionnaire:
          - type: text
            label: eMail
            name: email
          - type: number
            label: Age
            name: age
            min: 0
            max: 100
            default: 30
          - type: likert
            name: gender
            label: Gender
            response:
             - value: female
               label: Female
             - value: male
               label: Male
             - value: other
               label: Other